name: Crawler Demo Action

on:
  schedule:
    - cron: "0 6 * * *"  # 台灣時間 20:55
  workflow_dispatch:      # 允許手動測試

jobs:
  crawler-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python Dependency
        run: pip3 install requests beautifulsoup4

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DC_WEBHOOK_URL }}
          content: "Start crawling data for CBAS"

      - name: Run crawler.py
        run: python cbas_crawler.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "crawler-bot"
          git config --global user.email "crawler-bot@gmail.com"
          git add . && git commit -m "daily crawl"
          git push origin main

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DC_WEBHOOK_URL }}
          content: "Finished crawling data for CBAS"
